# Generated by Django 5.0.4 on 2024-05-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_payments_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_status',
            field=models.TextField(blank=True, null=True, verbose_name='статус оплаты'),
        ),
    ]
