# Generated by Django 5.0.4 on 2024-05-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_lesson_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='lesson',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее обновление'),
        ),
    ]
