# Generated by Django 5.0.4 on 2024-05-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0010_remove_lesson_updated_at_lesson_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='last_update',
        ),
        migrations.AddField(
            model_name='course',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее обновление'),
        ),
    ]
